export type JobStatus = '접수중' | '마감임박' | '마감완료'

export interface JobPosting {
  id: string
  postedAt: string
  company: string
  title: string
  recommended?: boolean
  status: JobStatus
  views: number
  deadline: string
  employmentType: string
  location: string
  source: string
  department: string
  summary: string
  requirements: string[]
  preferred: string[]
  process: string[]
  imageUrl?: string
}

const baseRequirements = ['관련 전공 또는 직무 경험 보유자', '문서 작성 및 협업 커뮤니케이션 가능자', '성실하고 책임감 있는 업무 태도']
const basePreferred = ['유관 프로젝트 경험', 'OA 및 협업 도구 활용 경험', '인근 거주자 또는 즉시 근무 가능자']
const baseProcess = ['서류전형', '1차 면접', '최종 합격']

export const JOB_POSTINGS: JobPosting[] = [
  {
    id: 'nexon-korea-game-service',
    postedAt: '2026-05-21',
    company: '넥슨코리아',
    title: '2026 NEXON KOREA 채용연계형 인턴십',
    recommended: true,
    status: '접수중',
    views: 421,
    deadline: '2026-06-10',
    employmentType: '채용연계형 인턴',
    location: '경기 성남시',
    source: '관리자 스크래핑 등록',
    department: '기술본부 / 글로벌보안본부 / 사회공헌팀',
    summary: '넥슨코리아에서 기술PM, DBA/SE, 프론트엔드 개발, 정보보안 등 다양한 직무의 채용연계형 인턴을 모집합니다.',
    requirements: ['기졸업자 및 2026년 8월 졸업예정자', '인턴 기간 Full-Time 근무 가능자', '해외여행 결격 사유가 없는 자'],
    preferred: ['게임 서비스와 플랫폼에 대한 관심', '개발 또는 보안 관련 프로젝트 경험', '문제 해결 중심의 협업 경험'],
    process: ['서류심사', '과제전형', '면접전형', '최종합격'],
    imageUrl: '/nexon-recruit.svg',
  },
  {
    id: 'nhn-web-frontend',
    postedAt: '2026-05-20',
    company: 'NHN',
    title: '웹 프론트엔드 개발 신입 채용',
    status: '접수중',
    views: 321,
    deadline: '2026-06-18',
    employmentType: '정규직',
    location: '경기 성남시',
    source: '관리자 스크래핑 등록',
    department: '플랫폼개발팀',
    summary: 'React 기반 서비스 화면 개발과 운영, 공통 컴포넌트 개선 업무를 수행합니다.',
    requirements: ['JavaScript/TypeScript 이해', 'React 프로젝트 경험', '웹 표준과 접근성 기본 이해'],
    preferred: ['상태관리 라이브러리 사용 경험', '테스트 코드 작성 경험', '디자인 시스템 협업 경험'],
    process: ['서류전형', '코딩테스트', '기술면접', '최종면접'],
  },
  {
    id: 'coupang-logistics-admin',
    postedAt: '2026-05-19',
    company: '쿠팡',
    title: '물류센터 운영지원 담당자 채용',
    status: '접수중',
    views: 97,
    deadline: '2026-06-05',
    employmentType: '정규직',
    location: '경남 창원시',
    source: '관리자 스크래핑 등록',
    department: '운영지원팀',
    summary: '물류센터 운영 데이터 관리, 현장 지원, 비용 정산 업무를 담당합니다.',
    requirements: ['엑셀 활용 가능자', '현장 커뮤니케이션 가능자', '교대 근무 가능자'],
    preferred: ['물류/유통 관련 경험', 'ERP 사용 경험', '창원 인근 거주자'],
    process: baseProcess,
  },
  {
    id: 'lg-cns-cloud-engineer',
    postedAt: '2026-05-18',
    company: 'LG CNS',
    title: '클라우드 엔지니어 신입 채용',
    recommended: true,
    status: '접수중',
    views: 275,
    deadline: '2026-06-14',
    employmentType: '정규직',
    location: '서울 강서구',
    source: '관리자 스크래핑 등록',
    department: '클라우드사업부',
    summary: '클라우드 인프라 구축, 운영 자동화, 모니터링 환경 개선 업무를 수행합니다.',
    requirements: ['Linux 기본 이해', '클라우드 서비스 학습 경험', '스크립트 작성 가능자'],
    preferred: ['AWS/Azure/GCP 사용 경험', 'Docker 또는 Kubernetes 경험', '인프라 프로젝트 경험'],
    process: ['서류전형', '인성검사', '기술면접', '최종면접'],
  },
  {
    id: 'samsung-sds-data-engineer',
    postedAt: '2026-05-17',
    company: '삼성SDS',
    title: '데이터 엔지니어 채용',
    status: '접수중',
    views: 302,
    deadline: '2026-06-20',
    employmentType: '정규직',
    location: '서울 송파구',
    source: '관리자 스크래핑 등록',
    department: '데이터플랫폼팀',
    summary: '데이터 파이프라인 개발, 품질 관리, 분석 플랫폼 운영 업무를 담당합니다.',
    requirements: ['SQL 활용 가능자', 'Python 데이터 처리 경험', '데이터베이스 기본 이해'],
    preferred: ['Spark 사용 경험', '대용량 데이터 처리 프로젝트 경험', '클라우드 데이터 플랫폼 경험'],
    process: ['서류전형', '코딩테스트', '직무면접', '임원면접'],
  },
  {
    id: 'naver-service-planner',
    postedAt: '2026-05-16',
    company: '네이버',
    title: '서비스 기획 체험형 인턴',
    status: '접수중',
    views: 198,
    deadline: '2026-06-07',
    employmentType: '인턴',
    location: '경기 성남시',
    source: '관리자 스크래핑 등록',
    department: '서비스기획팀',
    summary: '사용자 리서치, 서비스 정책 정리, 화면 기획 보조 업무를 수행합니다.',
    requirements: ['서비스 기획 직무 관심자', '문서화 능력 보유자', '3개월 이상 근무 가능자'],
    preferred: ['Figma 사용 경험', '사용자 리서치 경험', 'IT 서비스 프로젝트 경험'],
    process: baseProcess,
  },
  {
    id: 'kakao-games-data-assistant',
    postedAt: '2026-05-15',
    company: '카카오게임즈',
    title: '데이터 분석 어시스턴트 모집',
    status: '마감임박',
    views: 186,
    deadline: '2026-05-24',
    employmentType: '인턴',
    location: '경기 성남시',
    source: '관리자 스크래핑 등록',
    department: '데이터전략팀',
    summary: '게임 지표 리포트 작성, 데이터 정제, 대시보드 운영 보조 업무를 담당합니다.',
    requirements: ['Python 또는 SQL 기초 지식', '데이터 분석 직무 관심자', '6개월 근무 가능자'],
    preferred: ['Tableau/Power BI 사용 경험', '게임 데이터 분석 프로젝트 경험', '통계 기초 이해'],
    process: ['서류전형', '과제전형', '면접'],
  },
  {
    id: 'hanhwang-industry-general-affairs',
    postedAt: '2026-05-04',
    company: '한황산업(주)밀양공장',
    title: '한황산업(주)밀양공장 총무 채용',
    recommended: true,
    status: '마감완료',
    views: 114,
    deadline: '2026-05-18',
    employmentType: '정규직',
    location: '경남 밀양시',
    source: '관리자 스크래핑 등록',
    department: '총무팀',
    summary: '공장 총무, 문서 관리, 근태 및 비품 관리 업무를 담당할 신입 및 경력 직원을 모집합니다.',
    requirements: ['초대졸 이상', '문서 작성 및 기본 OA 활용 가능자', '원활한 커뮤니케이션 역량 보유자'],
    preferred: ['제조업 총무 업무 경험', '운전 가능자', '인근 거주자'],
    process: baseProcess,
  },
  ...[
    ['woowa-product-manager', '우아한형제들', '프로덕트 매니저 신입 채용', '접수중', '서울 송파구'],
    ['line-plus-backend', 'LINE Plus', '백엔드 서버 개발자 채용', '접수중', '경기 성남시'],
    ['musinsa-commerce-md', '무신사', '커머스 MD 인턴 모집', '접수중', '서울 성동구'],
    ['hyundai-autoever-security', '현대오토에버', '정보보안 운영 담당자 채용', '접수중', '서울 강남구'],
    ['lotte-data-analyst', '롯데정보통신', '데이터 분석 컨설턴트 채용', '접수중', '서울 금천구'],
    ['ncsoft-qa', '엔씨소프트', '게임 QA 담당자 모집', '마감임박', '경기 성남시'],
    ['netmarble-publishing', '넷마블', '게임 퍼블리싱 운영 채용', '마감임박', '서울 구로구'],
    ['toss-cx-operator', '토스', 'CX 운영 매니저 채용', '마감임박', '서울 강남구'],
    ['cj-olive-network', 'CJ올리브네트웍스', 'IT서비스 운영 신입 채용', '마감임박', '서울 용산구'],
    ['kt-dx-consultant', 'KT', 'DX 컨설팅 어시스턴트 모집', '마감완료', '서울 종로구'],
    ['sk-planet-marketing-data', 'SK플래닛', '마케팅 데이터 분석 인턴', '마감완료', '경기 성남시'],
    ['hanwha-systems-sw', '한화시스템', 'SW 개발 신입 채용', '마감완료', '경기 용인시'],
  ].map(([id, company, title, status, location], index) => ({
    id,
    postedAt: `2026-05-${String(14 - index).padStart(2, '0')}`,
    company,
    title,
    status: status as JobStatus,
    views: 90 + index * 17,
    deadline: status === '마감완료' ? '2026-05-20' : '2026-06-15',
    employmentType: index % 3 === 0 ? '인턴' : '정규직',
    location,
    source: '관리자 스크래핑 등록',
    department: '채용부서',
    summary: `${company}에서 ${title} 포지션에 적합한 인재를 모집합니다.`,
    requirements: baseRequirements,
    preferred: basePreferred,
    process: baseProcess,
  })),
]
