-- Generated once from careerProcess.ts; operational changes must not regenerate applied migrations.
INSERT INTO dc.code_group(group_code,label,managed_by,fixed_codes) VALUES ('STUDENT_TYPE','학생 유형','OPERATIONAL',true);
INSERT INTO dc.code_group(group_code,label,managed_by,fixed_codes) VALUES ('COUNSEL_TOPIC','상담 주제','OPERATIONAL',false);
INSERT INTO dc.code_group(group_code,label,managed_by,fixed_codes) VALUES ('DIAGNOSIS_TEST','진단 검사','OPERATIONAL',true);
INSERT INTO dc.code_group(group_code,label,managed_by,fixed_codes) VALUES ('COUNSEL_STATUS','상담 상태','STRUCTURAL',true);
INSERT INTO dc.code_group(group_code,label,managed_by,fixed_codes) VALUES ('COUNSEL_TYPE','상담 구분','STRUCTURAL',true);
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('STUDENT_TYPE','T1','진로탐색형',0,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('STUDENT_TYPE','T2','진로설정형',1,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('STUDENT_TYPE','T3','역량성장형',2,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('STUDENT_TYPE','T4','취업준비형',3,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('STUDENT_TYPE','T5','취약관리형',4,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('STUDENT_TYPE','T6','우수인재형',5,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A01','자기이해 및 흥미 탐색',6,'{"type":"T1","goal":"성격·흥미·가치관 이해로 진로 방향 인식"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A02','강점 및 역량 탐색',7,'{"type":"T1","goal":"보유 강점을 언어화해 진로 대안 근거 확보"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A03','전공기반 진출분야 분석',8,'{"type":"T1","goal":"전공과 산업·직무의 연결 구조 이해"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A04','진로분야 직업군 탐색',9,'{"type":"T1","goal":"관심 직업군을 3개 내외로 압축"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A05','진로의사결정',10,'{"type":"T2","goal":"복수 대안 중 목표 진로 확정"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A06','목표 직무 구체화',11,'{"type":"T2","goal":"목표 직무를 채용공고 수준으로 구체화"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A07','직무기초역량 진단·설계',12,'{"type":"T2","goal":"목표 직무 대비 역량 갭 산출"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A08','경력개발 로드맵 설계',13,'{"type":"T2","goal":"로드맵 3축 실행계획 수립"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A09','실무 프로젝트 설계·수행',14,'{"type":"T3","goal":"직무 역량을 산출물로 증명"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A10','직무 실습·현장경험 설계',15,'{"type":"T3","goal":"현장실습·일경험 참여 설계"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A11','전공심화·자격취득 설계',16,'{"type":"T3","goal":"목표 직무 요구 자격·교육 이수 계획"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A12','멘토링 매칭·활용',17,'{"type":"T3","goal":"현직자 멘토로 직무 현실 검증"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A13','입사지원서 클리닉',18,'{"type":"T4","goal":"이력서·자기소개서 완성도 제고"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A14','포트폴리오·직무 증빙 구성',19,'{"type":"T4","goal":"역량을 증빙 자료로 구조화"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A15','모의면접·실전 코칭',20,'{"type":"T4","goal":"면접 대응력 향상"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A16','채용정보 탐색·지원전략',21,'{"type":"T4","goal":"지원 기업군과 전형 일정 관리"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A17','1:1 집중상담(진로 동기 회복)',22,'{"type":"T5","goal":"참여 동기 회복, 상담 관계 형성"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A18','학업·진로 병행 점검',23,'{"type":"T5","goal":"학사 일정과 진로 준비 병행 조정"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A19','소그룹 진로코칭',24,'{"type":"T5","goal":"또래 집단으로 참여 지속"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A20','이탈 방지 사후 점검',25,'{"type":"T5","goal":"미참여·중도이탈 학생 재연결"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A21','핵심기업 연계·매칭',26,'{"type":"T6","goal":"우수기업 매칭 및 사전 준비 점검"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A22','인턴십 설계·수행',27,'{"type":"T6","goal":"인턴십 참여 및 성과 관리"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A23','채용연계 전형 대비',28,'{"type":"T6","goal":"공채·수시 전형 단계별 대비"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TOPIC','A24','리더십·퍼스널 브랜딩',29,'{"type":"T6","goal":"성과를 브랜딩하고 확산"}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','CCORE','C-CORE 핵심진단검사',30,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','C1','C-1 진로탐색 진단검사',31,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','C2','C-2 진로설정 진단검사',32,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','C3','C-3 역량수준 진단검사',33,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','C4','C-4 구직역량 진단검사',34,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','C5','C-5 취약요인 진단검사',35,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('DIAGNOSIS_TEST','C6','C-6 우수인재 진단검사',36,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_STATUS','REQ','대기',37,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_STATUS','CONFIRMED','확정',38,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_STATUS','DONE','완료',39,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_STATUS','CANCEL_UNKNOWN','취소',40,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_STATUS','CANCEL_STU','취소',41,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_STATUS','CANCEL_CNS','취소',42,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TYPE','CAREER','진로상담',43,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TYPE','JOB','취업상담',44,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TYPE','PSY','심리',45,'{}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES ('COUNSEL_TYPE','PROF','교수',46,'{}');
