INSERT INTO dc.auth_role(role_code,label) VALUES('career','career');
INSERT INTO dc.auth_role(role_code,label) VALUES('psych','psych');
INSERT INTO dc.auth_role(role_code,label) VALUES('professor','professor');
INSERT INTO dc.auth_role(role_code,label) VALUES('assistant','assistant');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('home',NULL,'admin','홈','/',1);
INSERT INTO dc.menu_auth VALUES('home','career');
INSERT INTO dc.menu_auth VALUES('home','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('diagnosis',NULL,'admin','진단 관리','/diagnosis/status',2);
INSERT INTO dc.menu_auth VALUES('diagnosis','career');
INSERT INTO dc.menu_auth VALUES('diagnosis','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('diagnosis.0','diagnosis','admin','검사 현황','/diagnosis/status',0);
INSERT INTO dc.menu_auth VALUES('diagnosis.0','career');
INSERT INTO dc.menu_auth VALUES('diagnosis.0','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel',NULL,'admin','상담 관리','/counsel/requests',3);
INSERT INTO dc.menu_auth VALUES('counsel','career');
INSERT INTO dc.menu_auth VALUES('counsel','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel.0','counsel','admin','신청 접수함','/counsel/requests',0);
INSERT INTO dc.menu_auth VALUES('counsel.0','career');
INSERT INTO dc.menu_auth VALUES('counsel.0','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel.1','counsel','admin','일정·예약','/counsel/schedule',1);
INSERT INTO dc.menu_auth VALUES('counsel.1','career');
INSERT INTO dc.menu_auth VALUES('counsel.1','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel.2','counsel','admin','상담일지','/counsel/journals',2);
INSERT INTO dc.menu_auth VALUES('counsel.2','career');
INSERT INTO dc.menu_auth VALUES('counsel.2','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel.3','counsel','admin','집단상담','/counsel/groups',3);
INSERT INTO dc.menu_auth VALUES('counsel.3','career');
INSERT INTO dc.menu_auth VALUES('counsel.3','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel.4','counsel','admin','심리검사 결과','/counsel/psych-tests',4);
INSERT INTO dc.menu_auth VALUES('counsel.4','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('counsel.5','counsel','admin','상담 통계','/counsel/stats',5);
INSERT INTO dc.menu_auth VALUES('counsel.5','career');
INSERT INTO dc.menu_auth VALUES('counsel.5','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('students',NULL,'admin','학생 관리','/students',4);
INSERT INTO dc.menu_auth VALUES('students','career');
INSERT INTO dc.menu_auth VALUES('students','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('students.0','students','admin','담당 학생 목록','/students',0);
INSERT INTO dc.menu_auth VALUES('students.0','career');
INSERT INTO dc.menu_auth VALUES('students.0','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('students.1','students','admin','전체 학생 목록','/students/all',1);
INSERT INTO dc.menu_auth VALUES('students.1','career');
INSERT INTO dc.menu_auth VALUES('students.1','psych');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('roadmap',NULL,'admin','로드맵 관리','/roadmap/create',5);
INSERT INTO dc.menu_auth VALUES('roadmap','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('roadmap.0','roadmap','admin','로드맵 생성','/roadmap/create',0);
INSERT INTO dc.menu_auth VALUES('roadmap.0','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('roadmap.1','roadmap','admin','변경 요청함','/roadmap/requests',1);
INSERT INTO dc.menu_auth VALUES('roadmap.1','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('roadmap.2','roadmap','admin','로드맵 이행률 현황','/roadmap/progress',2);
INSERT INTO dc.menu_auth VALUES('roadmap.2','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('programs',NULL,'admin','비교과 운영','/programs',6);
INSERT INTO dc.menu_auth VALUES('programs','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('programs.0','programs','admin','프로그램 목록','/programs',0);
INSERT INTO dc.menu_auth VALUES('programs.0','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('programs.1','programs','admin','프로그램 관리','/programs/manage',1);
INSERT INTO dc.menu_auth VALUES('programs.1','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('programs.2','programs','admin','프로그램 등록','/programs/new',2);
INSERT INTO dc.menu_auth VALUES('programs.2','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('programs.3','programs','admin','블랙리스트','/programs/blacklist',3);
INSERT INTO dc.menu_auth VALUES('programs.3','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('jobs',NULL,'admin','채용공고','/jobs',7);
INSERT INTO dc.menu_auth VALUES('jobs','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('jobs.0','jobs','admin','교내 공고 목록','/jobs',0);
INSERT INTO dc.menu_auth VALUES('jobs.0','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('jobs.1','jobs','admin','교내공고 관리','/jobs/manage',1);
INSERT INTO dc.menu_auth VALUES('jobs.1','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('jobs.2','jobs','admin','공고 등록','/jobs/new',2);
INSERT INTO dc.menu_auth VALUES('jobs.2','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('jobs.3','jobs','admin','외부 공고 목록','/jobs/external',3);
INSERT INTO dc.menu_auth VALUES('jobs.3','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('jobs.4','jobs','admin','추천채용 지원자관리','/jobs/applicants',4);
INSERT INTO dc.menu_auth VALUES('jobs.4','career');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-advisees',NULL,'admin','지도학생','/professor/advisees',8);
INSERT INTO dc.menu_auth VALUES('prof-advisees','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-students',NULL,'admin','학생 검색','/professor/students',9);
INSERT INTO dc.menu_auth VALUES('prof-students','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-counsel',NULL,'admin','상담 관리','/professor/counsel/requests',10);
INSERT INTO dc.menu_auth VALUES('prof-counsel','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-counsel.0','prof-counsel','admin','신청 접수','/professor/counsel/requests',0);
INSERT INTO dc.menu_auth VALUES('prof-counsel.0','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-counsel.1','prof-counsel','admin','상담 기록','/professor/counsel/records',1);
INSERT INTO dc.menu_auth VALUES('prof-counsel.1','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-setup',NULL,'admin','상담 설정','/professor/schedule',11);
INSERT INTO dc.menu_auth VALUES('prof-setup','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-setup.0','prof-setup','admin','상담 제한일정','/professor/schedule',0);
INSERT INTO dc.menu_auth VALUES('prof-setup.0','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('prof-setup.1','prof-setup','admin','상담 노출 설정','/professor/profile',1);
INSERT INTO dc.menu_auth VALUES('prof-setup.1','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('asst-students',NULL,'admin','학생 현황','/assistant/students',12);
INSERT INTO dc.menu_auth VALUES('asst-students','assistant');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('asst-advisor',NULL,'admin','전담교수','/assistant/advisor',13);
INSERT INTO dc.menu_auth VALUES('asst-advisor','assistant');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('asst-advisor.0','asst-advisor','admin','배정 현황','/assistant/advisor',0);
INSERT INTO dc.menu_auth VALUES('asst-advisor.0','assistant');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('asst-advisor.1','asst-advisor','admin','상담 실적','/assistant/advisor/records',1);
INSERT INTO dc.menu_auth VALUES('asst-advisor.1','assistant');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('asst-companies',NULL,'admin','학과추천기업관리','/assistant/companies',14);
INSERT INTO dc.menu_auth VALUES('asst-companies','assistant');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('settings',NULL,'admin','설정','/settings',15);
INSERT INTO dc.menu_auth VALUES('settings','career');
INSERT INTO dc.menu_auth VALUES('settings','psych');
INSERT INTO dc.menu_auth VALUES('settings','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('settings.0','settings','admin','내 프로필','/settings',0);
INSERT INTO dc.menu_auth VALUES('settings.0','career');
INSERT INTO dc.menu_auth VALUES('settings.0','psych');
INSERT INTO dc.menu_auth VALUES('settings.0','professor');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('settings.1','settings','admin','가능 시간대','/settings/availability',1);
INSERT INTO dc.menu_auth VALUES('settings.1','career');
INSERT INTO dc.menu_auth VALUES('settings.1','psych');
