-- 시스템관리자 상단바 — 현행 관리자 메뉴 트리(CURRENT.md §1-3)와 시스템관리 좌측 메뉴 15개를 옮긴다.
-- 화면이 있는 것은 메뉴관리·코드관리·변경 이력·이관 확인 사항·학과 담당 배정·공지 관리뿐이고 나머지는 자리(NotReady)다.
-- menu_code 는 navConfig.ts 의 섹션 id 와 child 인덱스로 맞춘다 — 순서를 바꾸면 라벨이 어긋난다.
UPDATE dc.menu SET sort_order=9,version=version+1 WHERE menu_code='system';
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-forecast',NULL,'admin','취업예측분석시스템','/forecast',1);
INSERT INTO dc.menu_auth VALUES('adm-forecast','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-members',NULL,'admin','회원관리','/members/assignments',2);
INSERT INTO dc.menu_auth VALUES('adm-members','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-diagnosis',NULL,'admin','진단관리','/diagnosis',3);
INSERT INTO dc.menu_auth VALUES('adm-diagnosis','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-counsel',NULL,'admin','상담관리','/counsel',4);
INSERT INTO dc.menu_auth VALUES('adm-counsel','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-roadmap',NULL,'admin','로드맵관리','/roadmap',5);
INSERT INTO dc.menu_auth VALUES('adm-roadmap','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-programs',NULL,'admin','비교과프로그램관리','/extracurricular',6);
INSERT INTO dc.menu_auth VALUES('adm-programs','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-companies',NULL,'admin','기업정보플랫폼','/companies',7);
INSERT INTO dc.menu_auth VALUES('adm-companies','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-notices',NULL,'admin','공지사항','/notices',8);
INSERT INTO dc.menu_auth VALUES('adm-notices','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('adm-members.0','adm-members','admin','학과 담당 배정','/members/assignments',0);
INSERT INTO dc.menu_auth VALUES('adm-members.0','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.0','system','admin','메뉴관리','/system/menus',0);
INSERT INTO dc.menu_auth VALUES('system.0','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.1','system','admin','그룹관리','/system/groups',1);
INSERT INTO dc.menu_auth VALUES('system.1','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.2','system','admin','권한관리','/system/auth',2);
INSERT INTO dc.menu_auth VALUES('system.2','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.3','system','admin','코드관리','/system/codes',3);
INSERT INTO dc.menu_auth VALUES('system.3','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.4','system','admin','게시판관리','/system/boards',4);
INSERT INTO dc.menu_auth VALUES('system.4','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.5','system','admin','배너관리','/system/banners',5);
INSERT INTO dc.menu_auth VALUES('system.5','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.6','system','admin','팝업관리','/system/popups',6);
INSERT INTO dc.menu_auth VALUES('system.6','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.7','system','admin','설문조사 관리','/system/surveys',7);
INSERT INTO dc.menu_auth VALUES('system.7','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.8','system','admin','사용자 접속이력','/system/access-log',8);
INSERT INTO dc.menu_auth VALUES('system.8','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.9','system','admin','업무접근 현황','/system/work-access',9);
INSERT INTO dc.menu_auth VALUES('system.9','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.10','system','admin','접속통계','/system/access-stats',10);
INSERT INTO dc.menu_auth VALUES('system.10','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.11','system','admin','접근경로','/system/access-path',11);
INSERT INTO dc.menu_auth VALUES('system.11','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.12','system','admin','관리자 IP관리','/system/admin-ip',12);
INSERT INTO dc.menu_auth VALUES('system.12','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.13','system','admin','권한변경이력','/system/auth-events',13);
INSERT INTO dc.menu_auth VALUES('system.13','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.14','system','admin','SMS 관리','/system/sms',14);
INSERT INTO dc.menu_auth VALUES('system.14','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.15','system','admin','변경 이력','/system/events',15);
INSERT INTO dc.menu_auth VALUES('system.15','AUTH0006');
INSERT INTO dc.menu(menu_code,parent_code,portal,label,route,sort_order) VALUES('system.16','system','admin','이관 확인 사항','/system/issues',16);
INSERT INTO dc.menu_auth VALUES('system.16','AUTH0006');
