-- 비교과 역량향상률 조사 — 사전(선발 후·운영 시작 전)·사후(수료 후) 같은 문항, 5점 Likert.
-- 영역·문항은 코드관리(dc.code_item)가 정본이라 관리자가 화면에서 고친다. 응답은 append-only.
-- 만족도 조사는 phase='SATISFACTION' 자리만 두고 문항은 양식이 오면 SURVEY_ITEM 에 추가한다.
-- Rollback: 엔드포인트를 내리고 응답 테이블은 보존한다.
SET LOCAL lock_timeout = '5s';
INSERT INTO dc.code_group(group_code,label,managed_by,fixed_codes,sort_order)
VALUES('SURVEY_AREA','설문 · 역량향상률 조사 영역','OPERATIONAL',false,98),
      ('SURVEY_ITEM','설문 · 조사 문항','OPERATIONAL',false,99);
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES
('SURVEY_AREA','CAREER_1','자기 이해·정체성 역량',1,'{"group":"CAREER","position":1}'),
('SURVEY_AREA','CAREER_2','진로 탐색·정보 활용 역량',2,'{"group":"CAREER","position":2}'),
('SURVEY_AREA','CAREER_3','진로 설계·의사결정 역량',3,'{"group":"CAREER","position":3}'),
('SURVEY_AREA','CAREER_4','경력개발 계획 역량',4,'{"group":"CAREER","position":4}'),
('SURVEY_AREA','CAREER_5','진로 적응·동기 역량',5,'{"group":"CAREER","position":5}'),
('SURVEY_AREA','JOB_1','직무이해·산업이해 역량',11,'{"group":"JOB","position":1}'),
('SURVEY_AREA','JOB_2','직무기초·전문기술 역량',12,'{"group":"JOB","position":2}'),
('SURVEY_AREA','JOB_3','문제해결·프로젝트 수행 역량',13,'{"group":"JOB","position":3}'),
('SURVEY_AREA','JOB_4','커뮤니케이션·협업 역량',14,'{"group":"JOB","position":4}'),
('SURVEY_AREA','JOB_5','경력관리·취업실전 역량',15,'{"group":"JOB","position":5}'),
('SURVEY_AREA','EMPLOY_1','취업준비도·전략 역량',21,'{"group":"EMPLOY","position":1}'),
('SURVEY_AREA','EMPLOY_2','직무적합·직무역량',22,'{"group":"EMPLOY","position":2}'),
('SURVEY_AREA','EMPLOY_3','취업실전 기술 역량',23,'{"group":"EMPLOY","position":3}'),
('SURVEY_AREA','EMPLOY_4','기업이해·조직적응 역량',24,'{"group":"EMPLOY","position":4}'),
('SURVEY_AREA','EMPLOY_5','취업유지·경력관리 역량',25,'{"group":"EMPLOY","position":5}');
INSERT INTO dc.code_item(group_code,code,label,sort_order,payload) VALUES
('SURVEY_ITEM','JOB_1_01','나는 관심 직무의 주요 업무 내용을 3가지 이상 설명할 수 있다.',1101,'{"areaKey":"JOB_1","position":1}'),
('SURVEY_ITEM','JOB_1_02','나는 해당 직무가 어떤 산업에서 채용되고 수행되는지 설명할 수 있다.',1102,'{"areaKey":"JOB_1","position":2}'),
('SURVEY_ITEM','JOB_1_03','나는 직무수행 과정에서 연관된 유관 부서(협업 부서)가 어디인지 알고, 업무 흐름을 설명할 수 있다.',1103,'{"areaKey":"JOB_1","position":3}'),
('SURVEY_ITEM','JOB_1_04','나는 해당 직무 전문가로 성장하기 위한 경력개발 방향(Career Path)을 알고 있다.',1104,'{"areaKey":"JOB_1","position":4}'),
('SURVEY_ITEM','JOB_2_01','나는 직무 관련 지식을 활용하여 직무와 관련된 실무적인 과제를 해결할 수 있다.',1201,'{"areaKey":"JOB_2","position":1}'),
('SURVEY_ITEM','JOB_2_02','나는 직무수행에 필수적인 도구(소프트웨어, 장비)나 기술을 능숙하게 조작할 수 있다.',1202,'{"areaKey":"JOB_2","position":2}'),
('SURVEY_ITEM','JOB_2_03','나는 실무에서 사용되는 전문용어를 이해하고, 이를 사용하여 원활하게 대화할 수 있다.',1203,'{"areaKey":"JOB_2","position":3}'),
('SURVEY_ITEM','JOB_2_04','나는 최신 기술이나 기법을 습득하기 위해 별도의 학습이나 훈련을 지속하고 있다.',1204,'{"areaKey":"JOB_2","position":4}'),
('SURVEY_ITEM','JOB_2_05','나는 직무 관련 전공 수업이나 교육과정에서 배운 이론을 실제 프로젝트에 적용해 본 경험이 있다.',1205,'{"areaKey":"JOB_2","position":5}'),
('SURVEY_ITEM','JOB_3_01','나는 프로젝트 수행 중 발생한 문제를 명확히 정의하고, 원인을 분석할 수 있다.',1301,'{"areaKey":"JOB_3","position":1}'),
('SURVEY_ITEM','JOB_3_02','나는 문제해결을 위해 객관적인 데이터나 근거 자료를 수집하여 대안을 제시할 수 있다.',1302,'{"areaKey":"JOB_3","position":2}'),
('SURVEY_ITEM','JOB_3_03','나는 창의적인 아이디어를 제안하여 기존의 방식을 개선해 본 경험이 있다.',1303,'{"areaKey":"JOB_3","position":3}'),
('SURVEY_ITEM','JOB_3_04','나는 프로젝트의 목표부터 결과까지 전 과정을 체계적으로 관리하고 완수해 본 경험이 있다.',1304,'{"areaKey":"JOB_3","position":4}'),
('SURVEY_ITEM','JOB_3_05','나는 복잡한 정보를 구조화하여 핵심 내용을 파악하는 논리적 사고력을 갖추고 있다.',1305,'{"areaKey":"JOB_3","position":5}'),
('SURVEY_ITEM','JOB_4_01','나는 직무수행 시 지켜야 할 법규와 윤리 강령이 무엇인지 알고 있으며 이를 준수한다.',1401,'{"areaKey":"JOB_4","position":1}'),
('SURVEY_ITEM','JOB_4_02','나는 업무상 알게 된 보안 사항이나 중요 정보를 철저히 관리할 수 있다.',1402,'{"areaKey":"JOB_4","position":2}'),
('SURVEY_ITEM','JOB_4_03','나는 동료 및 상사와의 관계에서 지켜야 할 기본적인 비즈니스 매너(인사, 호칭 등)를 알고 있다.',1403,'{"areaKey":"JOB_4","position":3}'),
('SURVEY_ITEM','JOB_4_04','나는 공과 사를 구별하고, 책임감 있게 맡은 업무를 완수하려는 태도를 가지고 있다.',1404,'{"areaKey":"JOB_4","position":4}'),
('SURVEY_ITEM','JOB_5_01','나는 나의 프로젝트 경험과 성과물을 체계적으로 정리한 직무 포트폴리오를 가지고 있다.',1501,'{"areaKey":"JOB_5","position":1}'),
('SURVEY_ITEM','JOB_5_02','나는 나의 경험 중 직무역량을 가장 잘 보여줄 수 있는 핵심 경험(Key Experience)을 선별할 수 있다.',1502,'{"areaKey":"JOB_5","position":2}'),
('SURVEY_ITEM','JOB_5_03','나는 활동의 결과뿐만 아니라 과정, 역할, 배운 점 등을 상세하게 기록해 두었다.',1503,'{"areaKey":"JOB_5","position":3}'),
('SURVEY_ITEM','JOB_5_04','나는 나의 직무역량을 증명할 수 있는 객관적인 증빙 자료(수료증, 상장, 결과물 등)를 관리하고 있다.',1504,'{"areaKey":"JOB_5","position":4}'),
('SURVEY_ITEM','JOB_5_05','나는 나의 진로목표와 연계하여 포트폴리오의 부족한 부분을 파악하고 보완할 계획이 있다.',1505,'{"areaKey":"JOB_5","position":5}'),
('SURVEY_ITEM','CAREER_1_01','나는 나의 핵심 강점 3가지와 보완해야 할 약점 2가지를 구체적인 사례를 들어 설명할 수 있다.',101,'{"areaKey":"CAREER_1","position":1}'),
('SURVEY_ITEM','CAREER_1_02','나는 직업 선택 시 가장 중요하게 생각하는 가치관(워라밸, 연봉, 성장 등)의 우선순위를 명확히 정했다.',102,'{"areaKey":"CAREER_1","position":2}'),
('SURVEY_ITEM','CAREER_1_03','나는 표준화된 심리검사(고용24, MBTI 등) 결과를 해석하여 나의 성향을 타인에게 소개할 수 있다.',103,'{"areaKey":"CAREER_1","position":3}'),
('SURVEY_ITEM','CAREER_1_04','나는 내가 좋아하는 일(흥미)과 잘하는 일(적성)의 차이를 구분하여 목록으로 작성할 수 있다.',104,'{"areaKey":"CAREER_1","position":4}'),
('SURVEY_ITEM','CAREER_1_05','나는 나의 성격적 특성이 향후 직업 생활에 어떤 영향을 미칠지 구체적으로 예측하여 설명할 수 있다.',105,'{"areaKey":"CAREER_1","position":5}'),
('SURVEY_ITEM','CAREER_2_01','나는 희망하는 직무나 산업에 대한 정보를 얻을 수 있는 공신력 있는 사이트나 경로를 3개 이상 알고 있다.',201,'{"areaKey":"CAREER_2","position":1}'),
('SURVEY_ITEM','CAREER_2_02','나는 관심 있는 직업의 하는 일, 자격 요건, 미래 전망 등을 조사하여 핵심 내용을 요약할 수 있다.',202,'{"areaKey":"CAREER_2","position":2}'),
('SURVEY_ITEM','CAREER_2_03','나는 수집된 다양한 진로 정보 중에서 나에게 유용한 정보를 선별하여 비판적으로 분석할 수 있다.',203,'{"areaKey":"CAREER_2","position":3}'),
('SURVEY_ITEM','CAREER_2_04','나는 최근 진로 관련 박람회, 설명회, 상담 등에 참여하여 정보를 수집한 경험이 있다.',204,'{"areaKey":"CAREER_2","position":4}'),
('SURVEY_ITEM','CAREER_2_05','나는 전공과 관련된 진출 분야(직업군) 리스트를 5가지 이상 나열할 수 있다.',205,'{"areaKey":"CAREER_2","position":5}'),
('SURVEY_ITEM','CAREER_3_01','나는 나의 적성과 직업 전망을 종합적으로 고려하여 최종적인 진로 목표(직업/분야)를 결정했다.',301,'{"areaKey":"CAREER_3","position":1}'),
('SURVEY_ITEM','CAREER_3_02','나는 내가 선택한 진로가 나에게 적합한 이유를 논리적인 근거를 들어 설득할 수 있다.',302,'{"areaKey":"CAREER_3","position":2}'),
('SURVEY_ITEM','CAREER_3_03','나는 플랜 A(최우선 목표)가 실패할 경우를 대비한 플랜 B(대안)를 가지고 있다.',303,'{"areaKey":"CAREER_3","position":3}'),
('SURVEY_ITEM','CAREER_3_04','나는 진로 결정 과정에서 의사결정 도구(SWOT 분석, 의사결정 매트릭스 등)를 활용해 본 적이 있다.',304,'{"areaKey":"CAREER_3","position":4}'),
('SURVEY_ITEM','CAREER_4_01','나는 진로 목표를 달성하기 위해 대학 재학 중 해야 할 일을 학년별/시기별로 구분하여 계획표를 작성했다.',401,'{"areaKey":"CAREER_4","position":1}'),
('SURVEY_ITEM','CAREER_4_02','나는 목표 달성을 위해 필요한 자격증, 대외활동, 인턴십 등의 구체적인 리스트를 가지고 있다.',402,'{"areaKey":"CAREER_4","position":2}'),
('SURVEY_ITEM','CAREER_4_03','나는 수립한 계획을 실천하기 위해 이번 학기에 달성해야 할 단기 목표를 명확히 알고 있다.',403,'{"areaKey":"CAREER_4","position":3}'),
('SURVEY_ITEM','CAREER_4_04','나는 교내 비교과 프로그램 중 나의 진로 로드맵에 필요한 과정이 무엇인지 파악하고 있다.',404,'{"areaKey":"CAREER_4","position":4}'),
('SURVEY_ITEM','CAREER_5_01','나는 진로 준비 과정에서 예상치 못한 어려움이 닥쳐도 긍정적으로 극복할 자신이 있다.',501,'{"areaKey":"CAREER_5","position":1}'),
('SURVEY_ITEM','CAREER_5_02','나는 진로 목표 달성을 위해 주도적으로 학습하고 활동하려는 강한 의지가 있다.',502,'{"areaKey":"CAREER_5","position":2}'),
('SURVEY_ITEM','CAREER_5_03','나는 진로 관련 활동을 수행할 때 시간 가는 줄 모를 정도로 몰입하는 편이다.',503,'{"areaKey":"CAREER_5","position":3}'),
('SURVEY_ITEM','CAREER_5_04','나는 실패나 실수로부터 배울 점을 찾아내어 다음 도전의 밑거름으로 삼는다.',504,'{"areaKey":"CAREER_5","position":4}'),
('SURVEY_ITEM','EMPLOY_1_01','나는 희망 기업의 채용 프로세스와 평가 기준을 정확히 파악하고 설명할 수 있다.',2101,'{"areaKey":"EMPLOY_1","position":1}'),
('SURVEY_ITEM','EMPLOY_1_02','나는 합격자들의 평균 스펙과 나의 현재 스펙을 비교하여 부족한 점(Gap)을 명확히 알고 있다.',2102,'{"areaKey":"EMPLOY_1","position":2}'),
('SURVEY_ITEM','EMPLOY_1_03','나는 지원 시기(상/하반기)에 맞춰 구체적인 취업 지원 전략(타임라인)을 수립했다.',2103,'{"areaKey":"EMPLOY_1","position":3}'),
('SURVEY_ITEM','EMPLOY_1_04','나는 최근 채용 시장의 트렌드(수시 채용, 블라인드 채용 등) 변화에 맞는 대응 전략을 마련하고 있다.',2104,'{"areaKey":"EMPLOY_1","position":4}'),
('SURVEY_ITEM','EMPLOY_2_01','나는 채용공고의 직무 기술서를 분석하여 핵심 요구 역량 키워드를 추출할 수 있다.',2201,'{"areaKey":"EMPLOY_2","position":1}'),
('SURVEY_ITEM','EMPLOY_2_02','나는 나의 다양한 경험을 직무역량 키워드와 연결하여 직무 적합성을 논리적으로 설명할 수 있다.',2202,'{"areaKey":"EMPLOY_2","position":2}'),
('SURVEY_ITEM','EMPLOY_2_03','나는 내가 왜 이 직무에 적합한 인재인지 1분 이내로 요약하여 말할 수 있다.',2203,'{"areaKey":"EMPLOY_2","position":3}'),
('SURVEY_ITEM','EMPLOY_2_04','나는 나의 직무 지식이나 경험이 해당 직무수행에 어떻게 기여할 수 있는지 구체적인 근거를 댈 수 있다.',2204,'{"areaKey":"EMPLOY_2","position":4}'),
('SURVEY_ITEM','EMPLOY_3_01','나는 나의 경험을 STAR 기법(상황-과제-행동-결과)에 맞춰 구조화된 자기소개서로 작성할 수 있다.',2301,'{"areaKey":"EMPLOY_3","position":1}'),
('SURVEY_ITEM','EMPLOY_3_02','나는 면접관의 의도를 파악하고, 이에 맞는 핵심 위주의 답변을 할 수 있다.',2302,'{"areaKey":"EMPLOY_3","position":2}'),
('SURVEY_ITEM','EMPLOY_3_03','나는 모의면접 상황에서 적절한 시선 처리, 자세, 목소리 톤 등 비언어적 요소를 활용할 수 있다.',2303,'{"areaKey":"EMPLOY_3","position":3}'),
('SURVEY_ITEM','EMPLOY_3_04','나는 1분 자기소개, 지원동기, 입사 후 포부 등 필수면접 질문에 대한 답변 스크립트가 준비되어 있다.',2304,'{"areaKey":"EMPLOY_3","position":4}'),
('SURVEY_ITEM','EMPLOY_3_05','나는 압박 질문이나 돌발 질문 상황에서도 당황하지 않고 유연하게 대처할 수 있다.',2305,'{"areaKey":"EMPLOY_3","position":5}'),
('SURVEY_ITEM','EMPLOY_4_01','나는 지원하고자 하는 기업의 비전, 인재상, 핵심 가치를 정확하게 알고 설명할 수 있다.',2401,'{"areaKey":"EMPLOY_4","position":1}'),
('SURVEY_ITEM','EMPLOY_4_02','나는 해당 기업의 최근 뉴스나 재무 상태 등을 분석하여 기업의 현황을 파악하고 있다.',2402,'{"areaKey":"EMPLOY_4","position":2}'),
('SURVEY_ITEM','EMPLOY_4_03','나는 경쟁사 대비 지원 기업만이 가진 강점과 약점을 분석하여 면접 답변에 활용할 수 있다.',2403,'{"areaKey":"EMPLOY_4","position":3}'),
('SURVEY_ITEM','EMPLOY_4_04','나는 기업 분석 내용을 바탕으로 내가 기여할 수 있는 점을 제시하여 입사 의지를 어필할 수 있다.',2404,'{"areaKey":"EMPLOY_4","position":4}'),
('SURVEY_ITEM','EMPLOY_4_05','나는 기업 분석을 위해 다트(DART), 지속가능경영보고서 등 전문 자료를 찾아보고 해석할 수 있다.',2405,'{"areaKey":"EMPLOY_4","position":5}'),
('SURVEY_ITEM','EMPLOY_5_01','나는 입사 후 3년, 5년, 10년 뒤의 성장 목표를 설정하고 경력관리 계획을 설명할 수 있다.',2501,'{"areaKey":"EMPLOY_5","position":1}'),
('SURVEY_ITEM','EMPLOY_5_02','나는 직장 생활 중 발생할 수 있는 스트레스나 슬럼프를 건강하게 관리하는 방법을 알고 있다.',2502,'{"areaKey":"EMPLOY_5","position":2}'),
('SURVEY_ITEM','EMPLOY_5_03','나는 평생 직업의 관점에서 지속적인 자기 계발이 필요함을 인식하고 학습 계획을 세우고 있다.',2503,'{"areaKey":"EMPLOY_5","position":3}');
CREATE TABLE dc.survey_response (
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 program_id text NOT NULL REFERENCES dc.program(id),
 student_uid text NOT NULL REFERENCES dc.student(intg_uid),
 phase text NOT NULL CHECK(phase IN ('PRE','POST','SATISFACTION')),
 snapshot jsonb NOT NULL DEFAULT '{}',
 submitted_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(program_id,student_uid,phase)
);
CREATE TABLE dc.survey_answer (
 response_id bigint NOT NULL REFERENCES dc.survey_response(id),
 item_group text NOT NULL DEFAULT 'SURVEY_ITEM' CHECK(item_group='SURVEY_ITEM'),
 item_code text NOT NULL,
 item_version integer NOT NULL CHECK(item_version>0),
 value smallint NOT NULL CHECK(value BETWEEN 1 AND 5),
 PRIMARY KEY(response_id,item_code),
 FOREIGN KEY(item_group,item_code) REFERENCES dc.code_item(group_code,code)
);
CREATE INDEX survey_answer_item ON dc.survey_answer(item_code) INCLUDE(value);
GRANT SELECT,INSERT ON dc.survey_response,dc.survey_answer TO dc_app;
GRANT USAGE,SELECT ON SEQUENCE dc.survey_response_id_seq TO dc_app;
