-- ══════════════════════════════════════════════════════════════════════════
-- K-2 (2차 수정본). EP_PRM 125컬럼 중 실제로 값이 들어 있는 컬럼 세기
--
--   1차 조립본이 ORA-00932 로 죽은 이유
--     COUNT(컬럼) 은 CLOB 에 쓸 수 없다. EP_PRM 에 CLOB 컬럼이 있다(DTL_CONT).
--     UNION ALL 로 묶는 순간 그 가지에서 타입 불일치가 난다.
--     → 전 컬럼을 SUM(CASE WHEN ... IS NULL THEN 0 ELSE 1 END) 으로 바꿨다.
--       LOB·문자·숫자·날짜 어디에나 통하고 결과는 COUNT 와 같다.
--
--   이 파일 전체가 "한 개의" SELECT 다 — 통째로 실행한다.
--
--   읽는 법: 값있음 = 807행 중 NULL 이 아닌 행 수
--     0     → 정의만 있고 한 번도 안 쓴 컬럼. 승계에서 뺀다.
--     1~8   → 사실상 미사용. 승계 전 담당자 확인.
--     807   → 필수값.
--
--   → out/k2.csv 로 저장해 주세요.
--   ⚠ 읽기 전용. 807행이라 몇 초면 끝납니다.
-- ══════════════════════════════════════════════════════════════════════════

SELECT '001 PRM_SEQ' AS "컬럼", SUM(CASE WHEN "PRM_SEQ" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '002 PRM_GB' AS "컬럼", SUM(CASE WHEN "PRM_GB" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '003 GROUP_GB' AS "컬럼", SUM(CASE WHEN "GROUP_GB" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '004 PRM_NM' AS "컬럼", SUM(CASE WHEN "PRM_NM" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '005 PRM_STAT_GB' AS "컬럼", SUM(CASE WHEN "PRM_STAT_GB" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '006 PRM_YEAR' AS "컬럼", SUM(CASE WHEN "PRM_YEAR" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '007 PRM_HAKGI' AS "컬럼", SUM(CASE WHEN "PRM_HAKGI" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '008 REQ_STAT_GB' AS "컬럼", SUM(CASE WHEN "REQ_STAT_GB" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '009 REQ_RTN_CONT' AS "컬럼", SUM(CASE WHEN "REQ_RTN_CONT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '010 PRM_DIV_CD' AS "컬럼", SUM(CASE WHEN "PRM_DIV_CD" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '011 NOTI_DATE' AS "컬럼", SUM(CASE WHEN "NOTI_DATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '012 APP_ST_DATE' AS "컬럼", SUM(CASE WHEN "APP_ST_DATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '013 APP_ED_DATE' AS "컬럼", SUM(CASE WHEN "APP_ED_DATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '014 PRM_ST_DATE' AS "컬럼", SUM(CASE WHEN "PRM_ST_DATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '015 PRM_ED_DATE' AS "컬럼", SUM(CASE WHEN "PRM_ED_DATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '016 PRM_CONT' AS "컬럼", SUM(CASE WHEN "PRM_CONT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '017 PRM_GOAL' AS "컬럼", SUM(CASE WHEN "PRM_GOAL" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '018 NEW_YN' AS "컬럼", SUM(CASE WHEN "NEW_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '019 NEW_CONT' AS "컬럼", SUM(CASE WHEN "NEW_CONT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '020 DEPT_CD' AS "컬럼", SUM(CASE WHEN "DEPT_CD" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '021 TEL' AS "컬럼", SUM(CASE WHEN "TEL" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '022 PLACE' AS "컬럼", SUM(CASE WHEN "PLACE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '023 PRM_GB_0' AS "컬럼", SUM(CASE WHEN "PRM_GB_0" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '024 PRM_GB_1' AS "컬럼", SUM(CASE WHEN "PRM_GB_1" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '025 PRM_GB_2' AS "컬럼", SUM(CASE WHEN "PRM_GB_2" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '026 PRM_GB_3' AS "컬럼", SUM(CASE WHEN "PRM_GB_3" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '027 PRM_NUM' AS "컬럼", SUM(CASE WHEN "PRM_NUM" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '028 SEL_NUM' AS "컬럼", SUM(CASE WHEN "SEL_NUM" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '029 ATT_YN' AS "컬럼", SUM(CASE WHEN "ATT_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '030 STAMP' AS "컬럼", SUM(CASE WHEN "STAMP" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '031 CAL_1' AS "컬럼", SUM(CASE WHEN "CAL_1" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '032 CAL_2' AS "컬럼", SUM(CASE WHEN "CAL_2" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '033 GRADE_YN' AS "컬럼", SUM(CASE WHEN "GRADE_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '034 NOTE' AS "컬럼", SUM(CASE WHEN "NOTE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '035 CAP_PER1' AS "컬럼", SUM(CASE WHEN "CAP_PER1" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '036 CAP_PER2' AS "컬럼", SUM(CASE WHEN "CAP_PER2" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '037 CAP_PER3' AS "컬럼", SUM(CASE WHEN "CAP_PER3" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '038 CAP_PER4' AS "컬럼", SUM(CASE WHEN "CAP_PER4" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '039 CAP_PER5' AS "컬럼", SUM(CASE WHEN "CAP_PER5" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '040 CAP_PER6' AS "컬럼", SUM(CASE WHEN "CAP_PER6" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '041 DTL_CONT' AS "컬럼", SUM(CASE WHEN "DTL_CONT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '042 CANCEL_DATE' AS "컬럼", SUM(CASE WHEN "CANCEL_DATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '043 CANCEL_NOTE' AS "컬럼", SUM(CASE WHEN "CANCEL_NOTE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '044 SURVEY_SEQ' AS "컬럼", SUM(CASE WHEN "SURVEY_SEQ" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '045 SURVEY_CNT' AS "컬럼", SUM(CASE WHEN "SURVEY_CNT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '046 SURVEY' AS "컬럼", SUM(CASE WHEN "SURVEY" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '047 RUN_RST' AS "컬럼", SUM(CASE WHEN "RUN_RST" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '048 EXPL' AS "컬럼", SUM(CASE WHEN "EXPL" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '049 MILEAGE_DIV' AS "컬럼", SUM(CASE WHEN "MILEAGE_DIV" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '050 POINT_DIV' AS "컬럼", SUM(CASE WHEN "POINT_DIV" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '051 POINT_YN' AS "컬럼", SUM(CASE WHEN "POINT_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '052 POINT1' AS "컬럼", SUM(CASE WHEN "POINT1" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '053 POINT2' AS "컬럼", SUM(CASE WHEN "POINT2" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '054 CAL_YN' AS "컬럼", SUM(CASE WHEN "CAL_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '055 FILE_INFO' AS "컬럼", SUM(CASE WHEN "FILE_INFO" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '056 CAREER_DEV_CD' AS "컬럼", SUM(CASE WHEN "CAREER_DEV_CD" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '057 POINT_ACT_TIME' AS "컬럼", SUM(CASE WHEN "POINT_ACT_TIME" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '058 REPORT1_YN' AS "컬럼", SUM(CASE WHEN "REPORT1_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '059 REPORT2_YN' AS "컬럼", SUM(CASE WHEN "REPORT2_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '060 REPORT3_YN' AS "컬럼", SUM(CASE WHEN "REPORT3_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '061 REPORT4_YN' AS "컬럼", SUM(CASE WHEN "REPORT4_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '062 REPORT5_YN' AS "컬럼", SUM(CASE WHEN "REPORT5_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '063 REPORT6_YN' AS "컬럼", SUM(CASE WHEN "REPORT6_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '064 REPORT7_YN' AS "컬럼", SUM(CASE WHEN "REPORT7_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '065 TRGT_STU' AS "컬럼", SUM(CASE WHEN "TRGT_STU" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '066 TRGT_STU11' AS "컬럼", SUM(CASE WHEN "TRGT_STU11" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '067 TRGT_STU12' AS "컬럼", SUM(CASE WHEN "TRGT_STU12" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '068 TRGT_STU13' AS "컬럼", SUM(CASE WHEN "TRGT_STU13" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '069 TRGT_STU14' AS "컬럼", SUM(CASE WHEN "TRGT_STU14" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '070 TRGT_STU15' AS "컬럼", SUM(CASE WHEN "TRGT_STU15" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '071 TRGT_STU21' AS "컬럼", SUM(CASE WHEN "TRGT_STU21" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '072 TRGT_STU22' AS "컬럼", SUM(CASE WHEN "TRGT_STU22" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '073 TRGT_STU23' AS "컬럼", SUM(CASE WHEN "TRGT_STU23" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '074 TRGT_STU24' AS "컬럼", SUM(CASE WHEN "TRGT_STU24" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '075 TRGT_STU31' AS "컬럼", SUM(CASE WHEN "TRGT_STU31" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '076 TRGT_STU32' AS "컬럼", SUM(CASE WHEN "TRGT_STU32" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '077 TRGT_STU33' AS "컬럼", SUM(CASE WHEN "TRGT_STU33" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '078 TRGT_STU34' AS "컬럼", SUM(CASE WHEN "TRGT_STU34" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '079 TRGT_STU35' AS "컬럼", SUM(CASE WHEN "TRGT_STU35" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '080 TRGT_STU41' AS "컬럼", SUM(CASE WHEN "TRGT_STU41" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '081 TRGT_STU42' AS "컬럼", SUM(CASE WHEN "TRGT_STU42" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '082 TRGT_STU51' AS "컬럼", SUM(CASE WHEN "TRGT_STU51" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '083 TRGT_STU52' AS "컬럼", SUM(CASE WHEN "TRGT_STU52" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '084 TRGT_STU53' AS "컬럼", SUM(CASE WHEN "TRGT_STU53" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '085 TRGT_STU61' AS "컬럼", SUM(CASE WHEN "TRGT_STU61" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '086 TRGT_STU62' AS "컬럼", SUM(CASE WHEN "TRGT_STU62" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '087 TRGT_STU63' AS "컬럼", SUM(CASE WHEN "TRGT_STU63" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '088 TRGT_EMP' AS "컬럼", SUM(CASE WHEN "TRGT_EMP" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '089 TRGT_EMP11' AS "컬럼", SUM(CASE WHEN "TRGT_EMP11" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '090 TRGT_EMP12' AS "컬럼", SUM(CASE WHEN "TRGT_EMP12" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '091 TRGT_EMP13' AS "컬럼", SUM(CASE WHEN "TRGT_EMP13" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '092 TRGT_EMP21' AS "컬럼", SUM(CASE WHEN "TRGT_EMP21" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '093 TRGT_EMP22' AS "컬럼", SUM(CASE WHEN "TRGT_EMP22" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '094 TRGT_EMP23' AS "컬럼", SUM(CASE WHEN "TRGT_EMP23" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '095 TRGT_EMP24' AS "컬럼", SUM(CASE WHEN "TRGT_EMP24" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '096 TRGT_EMP25' AS "컬럼", SUM(CASE WHEN "TRGT_EMP25" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '097 TRGT_EMP31' AS "컬럼", SUM(CASE WHEN "TRGT_EMP31" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '098 TRGT_EMP32' AS "컬럼", SUM(CASE WHEN "TRGT_EMP32" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '099 TRGT_OUT' AS "컬럼", SUM(CASE WHEN "TRGT_OUT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '100 OPEN_YN' AS "컬럼", SUM(CASE WHEN "OPEN_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '101 NOTICE_YN' AS "컬럼", SUM(CASE WHEN "NOTICE_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '102 REGID' AS "컬럼", SUM(CASE WHEN "REGID" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '103 REGDATE' AS "컬럼", SUM(CASE WHEN "REGDATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '104 UPDID' AS "컬럼", SUM(CASE WHEN "UPDID" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '105 UPDDATE' AS "컬럼", SUM(CASE WHEN "UPDDATE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '106 POINT_ACT_TIME2' AS "컬럼", SUM(CASE WHEN "POINT_ACT_TIME2" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '107 ACT_PNT' AS "컬럼", SUM(CASE WHEN "ACT_PNT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '108 PRSN_INFO_CNTN' AS "컬럼", SUM(CASE WHEN "PRSN_INFO_CNTN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '109 SEL_NUM_FST_YN' AS "컬럼", SUM(CASE WHEN "SEL_NUM_FST_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '110 CAREER_APP_RSN' AS "컬럼", SUM(CASE WHEN "CAREER_APP_RSN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '111 PRM_NM_ENG' AS "컬럼", SUM(CASE WHEN "PRM_NM_ENG" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '112 SURVEY_END' AS "컬럼", SUM(CASE WHEN "SURVEY_END" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '113 PRM_EXPL' AS "컬럼", SUM(CASE WHEN "PRM_EXPL" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '114 MIN_MILEAGE' AS "컬럼", SUM(CASE WHEN "MIN_MILEAGE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '115 MAX_MILEAGE' AS "컬럼", SUM(CASE WHEN "MAX_MILEAGE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '116 MIN_POINT' AS "컬럼", SUM(CASE WHEN "MIN_POINT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '117 MAX_POINT' AS "컬럼", SUM(CASE WHEN "MAX_POINT" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '118 PRM_GB_4' AS "컬럼", SUM(CASE WHEN "PRM_GB_4" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '119 SURVEY_ONLINE' AS "컬럼", SUM(CASE WHEN "SURVEY_ONLINE" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '120 AUTO_SMS' AS "컬럼", SUM(CASE WHEN "AUTO_SMS" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '121 DTAL_CLS_CD' AS "컬럼", SUM(CASE WHEN "DTAL_CLS_CD" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '122 DGE_DUP_APLC_YN' AS "컬럼", SUM(CASE WHEN "DGE_DUP_APLC_YN" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '123 PGM_HCLS_CD' AS "컬럼", SUM(CASE WHEN "PGM_HCLS_CD" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '124 PGM_SCLS_CD' AS "컬럼", SUM(CASE WHEN "PGM_SCLS_CD" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM UNION ALL
SELECT '125 COMP_TIME' AS "컬럼", SUM(CASE WHEN "COMP_TIME" IS NULL THEN 0 ELSE 1 END) AS "값있음" FROM EP_PRM
 ORDER BY 1;
